#!/bin/sh
readonly REQUIRED_KTLINT_VERSION=0.50.0
readonly KTLINT_INSTALL_GUIDE_LINK=https://pinterest.github.io/ktlint/$REQUIRED_KTLINT_VERSION/install/cli/#package-managers

# check ktlint installation
if ! [ -x "$(command -v ktlint)" ]; then
  printf 'ktlint 가 설치되어 있지 않습니다 !!\n\n아래 링크를 확인해 ktlint 를 설치해주세요.\n%s\n' $KTLINT_INSTALL_GUIDE_LINK
  exit 1
fi

# check ktlint version
local_ktlint_version="$(printf '%s\n' "$REQUIRED_KTLINT_VERSION" "$(ktlint --version)" | sort -V | head -n1)"
if [ "$local_ktlint_version" != "$REQUIRED_KTLINT_VERSION" ]; then
  printf 'ktlint 버전 업데이트가 필요합니다!\n\필요 버전: %s\현재 버전: %s.' "$REQUIRED_KTLINT_VERSION" "$local_ktlint_version"
  printf '위의 필요 버전으로 업데이트를 진행해주세요. (ex: brew upgrade ktlint)\n'
  exit 1
fi

# execute ktlint
if ! git diff --name-only --cached --relative \
  | grep --color=never '\.kt[s"]\?$' \
  | xargs ktlint --code-style=ktlint_official --relative; then
    printf '\nktlint 가 실패했습니다.\n커밋 이전에 변경사항을 확인해 ktlint 를 통과시켜주세요 !\n'
  exit 1
fi

